# Generated by Django 5.1.6 on 2025-03-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='uploded_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='descreption',
            new_name='description',
        ),
    ]
